# Generated by Django 2.2.2 on 2019-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='length',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='magnet',
        ),
    ]
