# Generated by Django 2.2.2 on 2019-07-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190713_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='info',
        ),
    ]
